[[specs]]
name = "client-server"
version = "r0.6.0"
release = "client_server/r0.6.0"
definitions_extra = ["event-schemas"]
blacklist = [
    "add3PID",
    "ban",
    "bind3PID",
    "changePassword",
    "checkUsernameAvailability",
    "claimKeys",
    "createRoom",
    "deactivateAccount",
    "delete3pidFromAccount",
    "deleteDevice",
    "deleteDevices",
    "deletePushRule",
    "deleteRoomAlias",
    "deleteRoomTag",
    "forgetRoom",
    "getAccount3PIDs",
    "getAccountData",
    "getAccountDataPerRoom",
    "getAvatarUrl",
    "getCapabilities",
    "getConfig",
    "getContent",
    "getContentOverrideName",
    "getContentThumbnail",
    "getDevice",
    "getDevices",
    "getDisplayName",
    "getEventContext",
    "getEvents",
    "getFilter",
    "getJoinedMembersByRoom",
    "getJoinedRooms",
    "getKeysChanges",
    "getMembersByRoom",
    "getNotifications",
    "getOneEvent",
    "getOneRoomEvent",
    "getProtocolMetadata",
    "getProtocols",
    "getPublicRooms",
    "getPushers",
    "getPushRule",
    "getPushRuleActions",
    "getRoomEvents",
    "getRoomIdByAlias",
    "getRoomState",
    "getRoomStateWithKey",
    "getRoomTags",
    "getRoomVisibilityOnDirectory",
    "getTurnServer",
    "getUrlPreview",
    "getUserProfile",
    "getWellknown",
    "getWhoIs",
    "initialSync",
    "inviteBy3PID",
    "inviteUser",
    "isPushRuleEnabled",
    "joinRoom",
    "joinRoomById",
    "kick",
    "leaveRoom",
    "logout_all",
    "peekEvents",
    "post3PIDs",
    "postPusher",
    "postReceipt",
    "queryKeys",
    "queryLocationByAlias",
    "queryLocationByProtocol",
    "queryPublicRooms",
    "queryUserByID",
    "queryUserByProtocol",
    "redactEvent",
    "redirectToSSO",
    "reportContent",
    "requestOpenIdToken",
    "requestTokenTo3PIDEmail",
    "requestTokenTo3PIDMSISDN",
    "requestTokenToRegisterEmail",
    "requestTokenToRegisterMSISDN",
    "requestTokenToResetPasswordEmail",
    "requestTokenToResetPasswordMSISDN",
    "roomInitialSync",
    "search",
    "searchUserDirectory",
    "sendMessage",
    "sendToDevice",
    "setAccountData",
    "setAccountDataPerRoom",
    "setAvatarUrl",
    "setDisplayName",
    "setPushRule",
    "setPushRuleActions",
    "setPushRuleEnabled",
    "setReadMarker",
    "setRoomAlias",
    "setRoomStateWithKey",
    "setRoomTag",
    "setRoomVisibilityOnDirectory",
    "setTyping",
    "unban",
    "unbind3pidFromAccount",
    "updateAppserviceRoomDirectoryVsibility",
    "updateDevice",
    "upgradeRoom",
    "uploadContent",
    "uploadKeys",
]

[[specs]]
name = "server-server"
version = "r0.1.3"
release = "server_server/release-r0.1.3"
blacklist = [
    "backfillRoom",
    "bulkPerspectivesKeyQuery",
    "claimUserEncryptionKeys",
    "compareEventAuth",
    "exchangeOpenIdToken",
    "exchangeThirdPartyInvite",
    "getEvent",
    "getEventAuth",
    "getMissingPreviousEvents",
    "getPublicRooms",
    "getRoomState",
    "getRoomStateIds",
    "getServerKey",
    "getUserDevices",
    "getVersion",
    "getWellKnown",
    "makeJoin",
    "makeLeave",
    "onBindThirdPartyIdentifier",
    "perspectivesKeyQuery",
    "queryInfo",
    "queryProfile",
    "queryRoomDirectory",
    "queryUserEncryptionKeys",
    "sendInviteV1",
    "sendInviteV2",
    "sendJoin",
    "sendLeave",
    "sendTransaction",
]